FROM ubuntu:latest

RUN apt update -y
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt update -y
RUN apt install -y python3.12 python3-pip python3-poetry curl

RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin/

WORKDIR /host
ADD pyproject.toml pyproject.toml
ADD poetry.lock poetry.lock
RUN poetry install --no-root

CMD [ "just", "serve" ]
